name = "TDTBWire"
uuid = "b4be49cf-15ca-4ac1-bc04-4f9b87ec2382"
authors = ["Cristián G. Sánchez"]
version = "0.1.0"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
